version: '3'

services:
  gmo-coin-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./src:/app/src"
    restart: unless-stopped
